### ISSUE TITLE
no any response to connect google

### ISSUE THREAD

**Issue by wukuan405** [sheetbase/cli#34]
nice project but no any response to connect google to try the service

```shell
$ node --version
v10.16.3

$ clasp --version
2.3.0

$ sheetbase --version
1.3.0

$ sheetbasgoogle connect -y

$ sheetbase google list
(node:9705) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@sheetbase/cli/src/commands/google/google-list.js:99:57)
    at step (/usr/local/lib/node_modules/@sheetbase/cli/src/commands/google/google-list.js:32:23)
    at Object.next (/usr/local/lib/node_modules/@sheetbase/cli/src/commands/google/google-list.js:13:53)
    at fulfilled (/usr/local/lib/node_modules/@sheetbase/cli/src/commands/google/google-list.js:4:58)
(node:9705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by lamnhan** [comment]
Hello,
Thank you for your report and I am sorry for the trouble you've got.
For me, it works just fine. Would you please try other older version (`1.2.0` or 1.1.0). If no version works, you may want to setup the project manually.
Actually, the `1x` versions are NOT tested properly. We are working on another better version. Until then, we keep the current version as is, that sounds suck, but we have no choice.
Thanks!

**Comment by wukuan405** [comment]
Thanks for your reply.
Just downgrade the version as you said, but still no any response to connect google, either no error log to debug. Could you give me further advise?
```sh
$ npm i @sheetbase/cli@1.2.0 -g

$ sheetbase --version
1.2.0

$ sheetbase google connect -y

```

**Comment by lamnhan** [comment]
Oh, that's a bad news. There are 2 choices now:
- First the CLI is an easy way to create and manage a Sheetbase project. But you can always manually create and manage any project (example below).
- You may want to wait for some time until we update and proper test a new version (the latest version works fine for me). Again, this sucks, but that is what it goes!

Example of manually using a Spreadsheet as a Database:

1. Create a Spreadsheet file in your Drive.
   + File ID (`1Abc...`) as the DB ID
   + Sheet name (ex. `posts`) as table name; gid (ex. `12345678`) as table id.
2. Follow [this](https://sheetbase.dev/doc/direct-database) to publish the sheets.
3. Using the [@sheetbase/client](https://sheetbase.dev/doc/javascript) to access the DB.
   + Add the script: <https://unpkg.com/@sheetbase/client@latest/dist/sheetbase.min.js>
   + Init the app:
   ```ts
      const app = sheetbase.initializeApp({
         backendUrl: '', // no need for this
         databaseId: [DB ID],
         databaseGids: {
            [table name]: [table id],
            // ex. post: '12345678'
         },
      });
   ```
   + Access database: `app.database()`

**Comment by wukuan405** [comment]
Great to know two choices.
Looking forward to your new release!

**Comment by lamnhan** [comment]
Thank you very much for your effort.
Will let you know when new version release.
Again, so sorry for the trouble!

**Comment by wukuan405** [comment]
hope could adapt and contribute to your solutions in production!
